Update p

diff --git a/bin/p b/bin/p
--- a/bin/p
+++ b/bin/p
@@ -3,24 +3,77 @@
 #
 # Setup.
 #
-
-VERSION="0.1.0"
+VERSION="1.0.23"
 UP=$'\033[A'
 DOWN=$'\033[B'
 P_PREFIX=${P_PREFIX-/usr/local}
 BASE_VERSIONS_DIR=$P_PREFIX/p/versions
+#configure flags eg: --enable-optimizations
+PY_INSTALL_FLAG=${PY_INSTALL_FLAG-}
 
+shell() {
+  export PATH=$BASE_VERSIONS_DIR/python:~/.local/bin:$PATH
+  get_current_version
+  export PATH=$BASE_VERSIONS_DIR/python/$current/bin:$PATH
+  bash --rcfile <(echo "export PS1='(py$current)[\w]> '")
+}
 #
 # Add to PATH.
 #
+ensurepath() {
+  if ! grep -q "export PATH=$BASE_VERSIONS_DIR/python:\$PATH" ~/.bashrc; then
+      echo -e "\nexport PATH=$BASE_VERSIONS_DIR/python:~/.local/bin:\$PATH" >> ~/.bashrc
+  fi
 
-if ! grep -q "export PATH=$BASE_VERSIONS_DIR/python:\$PATH" ~/.bashrc; then
-    echo -e "\nexport PATH=$BASE_VERSIONS_DIR/python:\$PATH" >> ~/.bashrc
-fi
+  if test -f ~/.zshrc && ! grep -q "export PATH=\"$BASE_VERSIONS_DIR/python:\$PATH\"" ~/.zshrc; then
+      echo -e "\nexport PATH=\"$BASE_VERSIONS_DIR/python:~/.local/bin:\$PATH\"" >> ~/.zshrc
+  fi
+  exec $SHELL
+}
 
-if ! grep -q "export PATH=\"$BASE_VERSIONS_DIR/python:\$PATH\"" ~/.zshrc; then
-    echo -e "\nexport PATH=\"$BASE_VERSIONS_DIR/python:\$PATH\"" >> ~/.zshrc
-fi
+# autoremove unused pkgs
+unpkg() {
+  test -z "$2" && abort "pip package name required"
+  export PATH=$BASE_VERSIONS_DIR/python:$PATH
+  python -m pip freeze |grep pip-autoremove || python -m pip install pip-autoremove
+  get_current_version
+  export PATH=$BASE_VERSIONS_DIR/python/$current/bin:$PATH
+  pip-autoremove $2
+}
+
+# 
+# migrate older package 
+#
+migration_failed() {
+  { echo
+    echo "MIGRATION FAILED"
+    echo "Inspect or clean up the package list at ${PIP_REQUIREMENTS}"
+  } 1>&2
+  exit 1
+}
+migrate() {
+  src="$2"
+  dst="$3"
+  (test -z "$2" || test -z "$3") && abort "version(s) required"
+
+  test -d "$BASE_VERSIONS_DIR"/python"/$src"  || {
+    echo "p: not an installed version: $src" 1>&2
+    exit 1
+  }
+
+  test -d "$BASE_VERSIONS_DIR"/python"/$dst"  || {
+    echo "p: not an installed version: $dst" 1>&2
+    exit 1
+  }
+  SEED="$(date "+%Y%m%d%H%M%S").$$"
+  PIP_REQUIREMENTS="/tmp/requirements.${SEED}.txt"
+
+  trap migration_failed ERR
+  "$BASE_VERSIONS_DIR/python/${src}/bin/python3" -m   pip freeze >> "${PIP_REQUIREMENTS}"
+  "$BASE_VERSIONS_DIR/python/${dst}/bin/python3" -m   pip install --requirement "${PIP_REQUIREMENTS}"
+  rm -f "${PIP_REQUIREMENTS}"
+  trap - ERR
+}
 
 #
 # Python source.
@@ -111,6 +164,13 @@ display_help() {
     p bin <version>                Output bin path for <version>
     p rm <version ...>             Remove the given version(s)
     p prev                         Revert to the previously activated version
+    p ensurepath                   Add python path to your search path
+    p unpkg <pkg ...>              Remove the given name(s) pip packages and unused dependencies
+    p shell                        Add python bin path to a new bash shell  
+    p p                            Wrapper pip command
+    p px                           Wrapper pipx command
+    p py                           Wrapper poetry command
+    p migrate <ver1> <ver2>        Migrate pip package from a Python version to another
     p ls                           Output the versions of Python available
       p ls latest                  Output the latest Python version available
       p ls stable                  Output the latest stable Python version available
@@ -120,6 +180,10 @@ display_help() {
     -V, --version   Output current version of p
     -h, --help      Display help information
 
+  Environment variables:
+
+    P_PREFIX        P cli and python install dir ,default:/usr/local
+    PY_INSTALL_FLAG Python install configure flags, eg:--enable-optimizations
 EOF
     exit 0
 }
@@ -208,7 +272,7 @@ check_current_version() {
     if test $? -eq 0; then
         get_current_version
         if diff &> /dev/null \
-            "$BASE_VERSIONS_DIR"/python/"$current"/python.exe \
+            "$BASE_VERSIONS_DIR"/python/"$current"/bin/python3 \
             "$(which python)" ; then
             active="python/$current"
         fi
@@ -321,7 +385,7 @@ activate() {
     if test "$version" != "$active"; then
         echo "$active" > "$BASE_VERSIONS_DIR"/.prev
 
-        ln -sf "$BASE_VERSIONS_DIR"/"$version"/python.exe "$BASE_VERSIONS_DIR"/python/python
+        ln -sf "$BASE_VERSIONS_DIR"/"$version"/bin/python3 "$BASE_VERSIONS_DIR"/python/python
     fi
 }
 
@@ -334,6 +398,7 @@ activate_previous() {
     local prev
     prev=$(cat "$BASE_VERSIONS_DIR"/.prev)
     test -d "$BASE_VERSIONS_DIR"/"$prev" || abort "previous version $prev not installed"
+    test ! -z "$prev" || abort "previous version $prev not installed"
     activate "$prev"
     echo
     get_current_version
@@ -376,17 +441,21 @@ install() {
         test "$version" || abort "invalid version ${1#v}"
     fi
 
-    local dir=$BASE_VERSIONS_DIR/python/$version
+    local dir=$BASE_VERSIONS_DIR/python/tmp/$version
+    local pydir=$BASE_VERSIONS_DIR/python/$version
     local url
     url=$(tarball_url "$version")
 
-    if test -d "$dir"; then
+    if test -d "$pydir"; then
         if [[ ! -e "$dir"/n.lock ]] ; then
             activate python/"$version"
 
             log activate "$version"
 
             get_current_version
+            
+            ln -sf "$pydir"/pip ~/.local/pipx/shared/bin/pip
+            "$pydir"/../python -m pipx reinstall-all
             success "Now using Python $current!"
 
             exit
@@ -416,12 +485,13 @@ install() {
     rm -f "$dir"/p.lock
 
     log configure "$version"
-    ./configure &> /dev/null
+    ./configure  "$PY_INSTALL_FLAG" --prefix=$BASE_VERSIONS_DIR/python/$version  --with-ensurepip=install  &> /dev/null
 
     log compile "$version"
-    make &> /dev/null
+    make -j 8 &> /dev/null
+    make install &> /dev/null
 
-    if [ ! -f "python.exe" ]; then
+    if [ ! -f "python" ]; then
     	abort "Unable to compile Python $version!"
     fi
 
@@ -429,12 +499,21 @@ install() {
     log activate "$version"
 
     source ~/.bashrc
-    source ~/.zshrc
+    test -f ~/.zshrc && source ~/.zshrc
     export PATH=$BASE_VERSIONS_DIR/python:$PATH
-    log refresh \$PATH
+    log refresh $PATH
+    log  install pipx 
+    python -m pip install pipx
+    mkdir -p ~/.local/pipx/shared/bin
+    ln -sf "$pydir"/pip ~/.local/pipx/shared/bin/pip
+    python -m pipx reinstall-all
+    log  install poetry
+    python -m pipx install poetry
 
     get_current_version
+    rm -rf "$dir"
     success "Now using Python $current!"
+    success "Now you can exec \`p ensurepath\` to add python bin PATH to .bashrc"
 }
 
 #
@@ -477,7 +556,7 @@ display_bin_path_for_version() {
         fi
     fi
 
-    local bin=$BASE_VERSIONS_DIR/python/$version/python.exe
+    local bin=$BASE_VERSIONS_DIR/python/$version/bin/python3
     if test -f "$bin"; then
         printf "%s \n" "$bin"
     else
@@ -499,7 +578,7 @@ execute_with_version() {
         version=$(display_latest_stable_version)
     fi
 
-    local bin=$BASE_VERSIONS_DIR/python/$version/python.exe
+    local bin=$BASE_VERSIONS_DIR/python/$version/bin/python3
 
     shift # remove version
 
@@ -623,6 +702,13 @@ else
             esac
             exit ;;
             prev|previous) activate_previous; exit ;;
+            ensurepath) ensurepath; exit ;;
+            unpkg) unpkg "$@"; exit ;;
+            migrate) migrate "$@"; exit ;;
+            shell) shell; exit ;;
+            p) python -m pip "${@:2}"; exit ;;
+            px) python -m pipx "${@:2}"; exit ;;
+            py) ~/.local/bin/poetry "${@:2}"; exit ;;
             default) activate_default; exit ;;
             latest) install "$($0 ls latest)"; exit ;;
             stable) install "$($0 ls stable)"; exit ;;
